"""Test support for Zerodha provider."""

from .mock_responses import (
    MOCK_INSTRUMENT_MASTER_CSV,
    MOCK_HISTORICAL_RESPONSE_MINUTE,
    MOCK_HISTORICAL_RESPONSE_DAY,
    MOCK_HISTORICAL_RESPONSE_WITH_OI,
    MOCK_AUTH_SUCCESS_RESPONSE,
    MOCK_AUTH_ERROR_RESPONSE,
    MOCK_RATE_LIMIT_ERROR_RESPONSE,
    MOCK_INVALID_PARAM_ERROR_RESPONSE,
    MOCK_EMPTY_DATA_RESPONSE,
    MOCK_USER_PROFILE_RESPONSE,
)

__all__ = [
    "MOCK_INSTRUMENT_MASTER_CSV",
    "MOCK_HISTORICAL_RESPONSE_MINUTE",
    "MOCK_HISTORICAL_RESPONSE_DAY",
    "MOCK_HISTORICAL_RESPONSE_WITH_OI",
    "MOCK_AUTH_SUCCESS_RESPONSE",
    "MOCK_AUTH_ERROR_RESPONSE",
    "MOCK_RATE_LIMIT_ERROR_RESPONSE",
    "MOCK_INVALID_PARAM_ERROR_RESPONSE",
    "MOCK_EMPTY_DATA_RESPONSE",
    "MOCK_USER_PROFILE_RESPONSE",
]